// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkNHRay7fxf10j3qgUGD3FWXv42i5Z72w',
    appId: '1:1046617815837:web:53a877ccd0c794ac043ff4',
    messagingSenderId: '1046617815837',
    projectId: 'chat-app-d17c9',
    authDomain: 'chat-app-d17c9.firebaseapp.com',
    storageBucket: 'chat-app-d17c9.appspot.com',
    measurementId: 'G-KGMX1F5LCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIM-9f1-6EOIS1Sekd0tVzCJ7TK46SvzE',
    appId: '1:526130814234:android:657b4007b51e43212760a3',
    messagingSenderId: '526130814234',
    projectId: 'chatapp-25fa4',
    storageBucket: 'chatapp-25fa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOKNRZQGDjTJWn6vEt-Iq1r-sh5ExEST8',
    appId: '1:526130814234:ios:49d7e5119209f9bb2760a3',
    messagingSenderId: '526130814234',
    projectId: 'chatapp-25fa4',
    storageBucket: 'chatapp-25fa4.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

}